### ISSUE TITLE
Add readme into the zipped file of the resultant files?

### ISSUE THREAD

**Issue by yukimoritani** [monodera/pfs_target_uploader#106]
Probably it is planned to make a document on uploader site itself, it will be nice to add a README file to the zipped file, just explaining what the each file is. I think a fixed file should be fine. For example, a file listing

>  * ppc_{upload_id}.ecsv : list of all simulated pointing center
>  * psl_{upload_id}.ecsv : summary table of PPP simulaition
>  ...

or something like this..

**Comment by monodera** [comment]
done
