### ISSUE TITLE
Not all objects are predicted to be 100% completion

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#122]
Some objects cannot be finished with 100% completion. I suppose that the online PPP should return pointings to complete the sample. I'll ask He-san.

**Comment by monodera** [comment]
It seems that this is a netflow issue. After a certain number of iterations, PPP gives up to continue.

**Comment by wanqqq31** [comment]
This problem is caused by otime set in netlfow. I do not know the exact reason of this bug (I will ask later). But after changing otime from 2024-05-20-08-00-00 to 2024-04-20-08-00-00, it works ok for the missing target.

**Comment by monodera** [comment]
Did you make a pull request? I happen to close it, but let's merge it first.

**Comment by wanqqq31** [comment]
Sorry this branch is a copy of u/wanqqq/PPP-exetime branch... If you already merge that branch (u/wanqqq/PPP-exetime) to the dev-main branch, I guess it should be ok. Please let me know if you did not do that. I will then make a new branch from dev-main about this issue.

**Comment by monodera** [comment]
sorry, I was meant to mention `issue/122-netflow-noAssign` branch. Can you check the PR #141 ?

**Comment by monodera** [comment]
ah, ok, I see what you mean. `otime` has already been changed to 2024-04-20-08-00-00, and I can ignore the content of the branch.
