### ISSUE TITLE
The output message about L vs M modes for the PPP simulation 

### ISSUE THREAD

**Issue by mihoishigaki** [monodera/pfs_target_uploader#124]
For a target list with only the medium-resolution mode for 
https://pfs-etc.naoj.hawaii.edu/uploader-dev/app

I got this:
 
The expected completion rate for low-resolution mode is 98%.
The expected completion rate for medium-resolution mode is nan%.

To reproduce:

1. Upload the target list (submitted target ID c1cbf792fd875433)
2. Validate and Simulate => successful 
3. See the messages above

**Comment by monodera** [comment]
fixed in 0f8eff6f9957b88420c0645808828b262766320d

I'll merge once He-san finishes the integration of new features.

**Comment by monodera** [comment]
I've updated it. Could you please check if the issue still persist? @mihoishigaki

**Comment by mihoishigaki** [comment]
I also confirmed that the issue has been resolved, running successfully for the med-res-only target list. Thank you so much for fixing.
