### ISSUE TITLE
Difference in PPCs for the same target list among different sessions. 

### ISSUE THREAD

**Issue by mihoishigaki** [monodera/pfs_target_uploader#125]
It may be what is expected (because of the statistical nature of the netflow), but I found the resulting PPCs are different among different sessions for the same target list. I tried three sessions and the resulting ROT and PPC are:

54.8 h   173 ppc
64.6 h   204 ppc
52.9 h   167 ppc

**Comment by monodera** [comment]
It seems a nature of netflow (and gurobi for solving the problem).
