### ISSUE TITLE
Files generated with the `download` button do not reflect slider positions

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#133]
**Describe the bug**
`ppc` and `psl` files generated with the `Download` button do not reflect the slider positions. 

**To Reproduce**
1. Simulate pointing
2. Click on 'Download' (1)
3. Change the slider positions
4. Click on 'Download' (2)

Compare the contents of `ppc` and `psl` lists.

**Expected behavior**
Files reflect the slider positions

**Comment by monodera** [comment]
I may be nice to set the initial slider position in the admin page so that it reflects the requested n_ppc rather than total n_ppc. not super urgent, though. @wanqqq31

**Comment by wanqqq31** [comment]
I set the initial value of slider in admin page to reflect the requested n_ppc now (f252e3f).

**Comment by monodera** [comment]
Thanks! Can you make a pull request?

**Comment by monodera** [comment]
Close the issue as it is fixed by #181
