### ISSUE TITLE
update documentation for December 2023 release (dev-main)

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#142]
It looks it's time to update documentation for `dev-main` branch and deploy it to the main app URL. 

Related issues:
#39 
#54

**Comment by monodera** [comment]
done #145

**Comment by monodera** [comment]
@yukimoritani @takagi-naoj (and Koshida-san) could you please check the updated documentation? I tried to incorporate your comment as much as possible. Currently the updated version is in the `dev` version. If update looks okay, I'd like to update the production version as well.

**Comment by monodera** [comment]
If you have further comments, please comment in this issue.

**Comment by takagi-naoj** [comment]
On the "Inputs" page, it says
"This is essentially equivalent to the following if no time constraint is specified."

I think that this sentence makes sense when "obs time window" is ready, but is "obs time window" already implemented?

**Comment by monodera** [comment]
No, it's not been implemented yet because the discussion is still on-going. I will remove the "if no time constraint is specified".

**Comment by mihoishigaki** [comment]
A word seems to be missing in the sentence: "The PFS Target Uploader is a web app to and submit the target list supplied by users with time estimate by a pointing simulation." in the top page?
