### ISSUE TITLE
ecsv file is failed?

### ISSUE THREAD

**Issue by mihoishigaki** [monodera/pfs_target_uploader#169]
I uploaded the attached an ecsv file and found the Validation status is "Failed". The csv file of the same content has been successfully loaded in ~10 seconds.  I'm wondering the file's ecsv version is not compatible with the uploader?

The header of the ecsv file looks like:
```
# %ECSV 1.0
# ---
# datatype:
# - {name: ob_code, datatype: string}
# - {name: obj_id, datatype: int64}
# - {name: ra, datatype: float64}
# - {name: dec, datatype: float64}
# - {name: equinox, datatype: string}
# - {name: priority, datatype: int64}
# - {name: exptime, datatype: float64}
# - {name: parallax, datatype: float64}
# - {name: pmra, datatype: float64}
# - {name: pmdec, datatype: float64}
# - {name: resolution, datatype: string}
# - {name: g_hsc, datatype: string, subtype: json}
# schema: astropy-2.0
```

**Comment by monodera** [comment]
One possible cause is that `g_hsc` is recognized as float. Can you share the full ecsv and error message?

**Comment by mihoishigaki** [comment]
Thanks for your comment. The file is in this link:
https://drive.google.com/file/d/1-MXCJY_Eomh0snzRi4DS23Rc9qXHJ3eB/view?usp=sharing

**Comment by monodera** [comment]
I found the cause. I implicitly assumed that columns of a .ecsv file is separated by space. I'm fixing it now.

**Comment by monodera** [comment]
#171 and #172 fix the issue. Can you check whether it's resolved or not?

**Comment by mihoishigaki** [comment]
Many thanks for the prompt fix. It seems the uploader currently does not start validating even for the example file. I guess this is a temporary thing. I will check again tomorrow.

**Comment by monodera** [comment]
sorry for the inconvenience. I believe that it's working properly now, and please try again when you have time.

**Comment by mihoishigaki** [comment]
Thanks a lot! I've just confirmed that the ecsv file has been successfully validated.
