### ISSUE TITLE
online PPP continues running for > 30min for a long target list (~18MB) 

### ISSUE THREAD

**Issue by mihoishigaki** [monodera/pfs_target_uploader#185]
I tried to upload a long target list (~18MB) 

https://drive.google.com/file/d/15IrufAHjc-nlAB_ztD00rdbxTM73zWWw/view?usp=sharing

as a mock filler program. The validation step was successful. Then, after clicking the "simulate" button, PPP continued running and didn't stop. As He-san suggested before, stopping PPP after 15-30min or allowing a user to stop and submit may be good.

**Comment by monodera** [comment]
It seems that the validation step was also failed. I suppose you didn't see the results in the main panel. I think it's simply the issue of the maximum file size. With ~65k objects, it's working. There might be a way to increase the maximum file size and I can set a large number. On the other hand, one proposal can have multiple catalogs, so splitting the original catalog to conform the size limit would also be fine.

**Comment by monodera** [comment]
65k objects (9346815 bytes) are okay, but 70k objects (10066626 bytes) are not.

**Comment by monodera** [comment]
I think I found a bug. Let me see.

**Comment by mihoishigaki** [comment]
Thanks for taking a look at the list. Yes, I can split the catalog and see how it works.

**Comment by monodera** [comment]
I fixed the error which was recorded in the log and deployed to the `uploader-dev` URL. Could you please try the development version?

**Comment by mihoishigaki** [comment]
I have confirmed that the target lists of up to 66K have been successfully validated and submitted (skipping the PPP simulation since they are fillers). Thanks a lot!

**Comment by monodera** [comment]
Thanks! I'll look at the list (also old ones as well).

BTW, I suppose the original file can also be validated (not sure, though).

**Comment by mihoishigaki** [comment]
That's great. The validation was indeed successful. I'm now submitting a combined list.

**Comment by mihoishigaki** [comment]
The validation and submission was also successful for the 130K list!
