### ISSUE TITLE
Number of ob_code is truncated

### ISSUE THREAD

**Issue by yukimoritani** [monodera/pfs_target_uploader#205]
When I validated the 100,000 targets, the number of ob_code (NL) on the left panel was truncated.
![image](https://github.com/monodera/pfs_target_uploader/assets/17194612/a857465e-320d-4beb-93a5-022d68fbf29f)

**Comment by monodera** [comment]
You can adjust the column width by dragging the cell border. Do you want to make the default width wider?

**Comment by monodera** [comment]
I've made a quick fix to the development version. I'm not sure if this works with other browser and computer environment.

![Screenshot 2024-05-25 at 20 03 37](https://github.com/monodera/pfs_target_uploader/assets/90394/6be94aa6-3b99-4710-b0dc-a55785854ac8)

**Comment by monodera** [comment]
@yukimoritani could you please check if you are happy with the layout when you have time?

**Comment by yukimoritani** [comment]
I'm sorry for my very late response. I tried and like the current layout.
