### ISSUE TITLE
Memory efficient clustering algorithm

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#256]
**Is your feature request related to a problem? Please describe.**
DBSCAN uses a lot of ram for a dense distribution. If there is a memory-efficient alternative, I'd like to switch to it. For example, ~45k objects in the COSMOS field uses all memory in the server including swaps, so it crashes with memory error.

**Describe the solution you'd like**
Maybe HDBSCAN? I'm not sure.

**Describe alternatives you've considered**
Ask to set more memory on the virtual machine (partly done).

**Comment by monodera** [comment]
@wanqqq31 Have you ever tested alternative clustering algorithms instead of DBSCAN? It seems to generate a distance matrix and the memory requirement would be up to O(n^2). If there is one providing similar-enough results with less memory usage like O(n) or O(nlogn), I'd like to consider it. I'll also google the possibilities.

**Comment by monodera** [comment]
I'm working on the `issue/256-memory-efficient-clustering-algorithm` branch to use `HDBSCAN`.

**Comment by wanqqq31** [comment]
I see, I have not noted this problem before. I will also work on it to find a better algorithm.

**Comment by monodera** [comment]
I think the current version at the branch above. I've deployed it to the dev URL.
